Port of Wiki Documentation to Website
Paperback-iOS/website pull request #79
Opened 2021-04-16 03:47 UTC by ConradWeiser

2021-05-17 04:47 UTC, ConradWeiser reviewed
For now, I think this is ready to go! We'll fine-tune as 0.6 comes out, providing new features and changing requirements slightly.

2021-05-19 18:56 UTC, FramboisePi requested changes
I think this regression came from Soitora's branch issues.

2021-05-19 18:56 UTC, FramboisePi commented on README.md
> +			<img src="https://github-readme-stats.vercel.app/api/pin/?username=Paperback-iOS&repo=app&bg_color=0000&text_color=777&hide_border=true" alt="Android App">
```suggestion
			<img src="https://github-readme-stats.vercel.app/api/pin/?username=Paperback-iOS&repo=app&bg_color=0000&text_color=777&hide_border=true" alt="iOS App">
```

2021-05-19 18:56 UTC, FramboisePi commented on README.md
> +			<img src="https://github-readme-stats.vercel.app/api/pin/?username=Paperback-iOS&repo=extensions-common&bg_color=0000&text_color=777&hide_border=true" alt="App Extensions">
```suggestion
			<img src="https://github-readme-stats.vercel.app/api/pin/?username=Paperback-iOS&repo=extensions-common&bg_color=0000&text_color=777&hide_border=true" alt="Extensions Common">
```

2021-05-19 19:00 UTC, FramboisePi approved these changes
👍 
I agree with the idea. Looks good to me. Some small changes can be addressed latter.

2021-05-19 19:08 UTC, merged